name: Merge gatekeeping

on:
  pull_request:
    types:
        - closed

jobs:
    merge_gatekeeper:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: check merge rules
              run: |
                echo "NOMERGE=FALSE" >> $GITHUB_ENV
                sleep 5
                export REPONAMECLEAN=`echo "${{ github.repository }}" | sed "s/'//g"`
                if [ "${{ github.event.pull_request.base.ref }}" == "main" ] && [ "${{ github.event.pull_request.head.ref }}" != "develop" ]
                  echo "Merging to main from a branch other than develop should not happen!"
                  echo "NOMERGE=TRUE" >> $GITHUB_ENV
                  echo "NOTIFY='Illegal push to main branch on $REPONAMECLEAN, build & deployment have been cancelled, please resolve.'"
                  if [ ${{ contains('hotfix', github.ref) }} ]
                    echo "NOMERGE=FALSE" >> $GITHUB_ENV
                    echo "NOTIFY='Illegal push to main branch on $REPONAMECLEAN, build & deployment have NOT been cancelled due to hotfix. Please merge main into dev if this deploy is a success.'" >> $GITHUB_ENV
                  fi
                fi
                exit 0

            - name: Kill running jobs
              if: contains(${{ env.NOMERGE }}, 'true')
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Slack notify example
              if: ${{ env.NOTIFY == 'true'}}
              run: |
                echo $NOTIFY
